[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/spa"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/opt/buildhome/cache/node_modules"

[functions]
  external_node_modules = ["express", "multer", "zod", "cors"]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

# Handle client-side routing (SPA) - catch all non-API routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
